language: python
python:
  - 3.6

services:
  - docker

before_install:
  - pip install flake8
  - flake8 .

install:
  - pip install -r requirements.txt

before_script:
  - pip --version
  - pip freeze

script:
  - echo "Done"
